<?php

$title = 'Account löschen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Sicher das du deinen Account löschen möchtest?
</p>
<?php
$url = $this->url('profile', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $profile->id; ?>" />
    <input type="submit" name="del" value="Ja" />
    <input type="submit" name="del" value="Nein" />
</div>
</form>