<?php $title = 'Benutzeradministration';?>
<?php $this->headTitle($title);?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php //echo $this->url('zfcuser/register', array('action' => 'register'));?>">
    <button class="btn btn-small btn-primary" type="button">Benutzer hinzufügen</button></a>
</p>
<table class="table">
<tr>
    <th>ID</th>
    <th>Benutzername</th>
    <th>E-Mail</th>
    <th>Anzeigename</th>
    <th>Login erlaubt?</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->user as $user) : ?>
<tr>
    <td><?php echo $this->escapeHtml($user->getUserId());?></td>
    <td><?php echo $this->escapeHtml($user->getUsername());?></td>
    <td><?php echo $this->escapeHtml($user->getEmail());?></td>
    <td><?php echo $this->escapeHtml($user->getDisplayName());?></td>
    <td><?php if ($this->escapeHtml($user->getLogin()) !== 1) :?>
        <i class="icon-ok-sign icon-white" alt="Login erlaubt"></i>
        <?php else: ?>
        <i class="icon-bann-circle icon-white" alt="Login nicht erlaubt"></i>
        <?php endif;?>
    </td>
    <td>
        <a href="<?php echo $this->url('useradmin',
            array('action' => 'edit', 'id' => $user->getUserId()));?>"><i class="icon-pencil" alt="Bearbeiten"></i></a>
        <a href="<?php echo $this->url('useradmin',
            array('action' => 'delete', 'id' => $user->getUserId()));?>"><i class="icon-trash" alt="Löschen"></i></a>
    </td>
</tr>
<?php endforeach; ?>
</table>